name: predict_env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy=1.10.1
  - matplotlib
  - pytest
  - seaborn
  - pip
  - gxx
  - bambi
  - pip:
    - scikit-learn
    - statsmodels
    - ipykernel
    - sphinx
    - ghp-import
    - pymc
    - ipywidgets
    - furo
    - jax==0.6.0